# Generated by Django 5.1.5 on 2025-03-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('url_pg', models.CharField(max_length=255, verbose_name='Строка подключения к PG')),
                ('url_wms', models.CharField(max_length=255, verbose_name='Название базы WMS')),
                ('prog_id', models.IntegerField(default=0, verbose_name='Код программы Логистика')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция в меню')),
                ('as_active', models.BooleanField(default=True, verbose_name='Признак активности')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ('position',),
            },
        ),
    ]
