# Generated by Django 5.1.5 on 2025-03-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция в меню')),
                ('as_active', models.BooleanField(default=True, verbose_name='Признак активности')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='base_app.filial', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ('position',),
            },
        ),
    ]
