# Generated by Django 5.1.5 on 2025-03-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='filial',
        ),
        migrations.AddField(
            model_name='menu',
            name='filial',
            field=models.ManyToManyField(related_name='menus', to='base_app.filial', verbose_name='Филиал'),
        ),
    ]
