# Generated by Django 5.1.4 on 2025-03-26 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_remove_menu_filial_menu_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='filial',
        ),
        migrations.AddField(
            model_name='menu',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='base_app.filial', verbose_name='Филиал'),
            preserve_default=False,
        ),
    ]
