# Generated by Django 5.1.4 on 2025-03-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_remove_menu_filial_menu_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция в меню')),
                ('as_active', models.BooleanField(default=True, verbose_name='Признак активности')),
                ('menu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='base_app.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ('position',),
            },
        ),
    ]
