# Generated by Django 5.1.4 on 2025-03-26 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_submenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('path_saved_order', models.CharField(max_length=255, verbose_name='Папка сохранения заявок XML')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция в меню')),
                ('as_active', models.BooleanField(default=True, verbose_name='Признак активности')),
                ('path_saved_reports', models.CharField(max_length=255, verbose_name='Папка сохранения отчетов')),
                ('id_groups_goods', models.IntegerField(default=0, verbose_name='Код папки товаров')),
                ('id_groups_vod', models.IntegerField(default=0, verbose_name='Код папки водителей, для ОК')),
                ('id_groups_vod_tls', models.IntegerField(default=0, verbose_name='Код папки водителей ТЛС, для ОК')),
                ('id_postav', models.IntegerField(blank=True, default=0, null=True, verbose_name='Код поставщика')),
                ('id_client', models.IntegerField(blank=True, default=0, null=True, verbose_name='Код клиента')),
                ('id_sklad', models.IntegerField(blank=True, default=0, null=True, verbose_name='Код склада')),
                ('id_agent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Код агента')),
                ('delivery_type', models.IntegerField(default=2, verbose_name='Тип доставки')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='base_app.filial', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ('position',),
            },
        ),
    ]
