# Generated by Django 5.1.4 on 2025-03-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_contracts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='filial',
            field=models.ManyToManyField(related_name='menus', to='base_app.filial', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='menu',
            field=models.ManyToManyField(default=1, related_name='menu', to='base_app.menu', verbose_name='Меню'),
        ),
    ]
