# Generated by Django 5.1.4 on 2025-03-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_remove_submenu_menu_submenu_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='menu',
        ),
        migrations.AddField(
            model_name='submenu',
            name='menu',
            field=models.ManyToManyField(default=1, related_name='menu', to='base_app.menu', verbose_name='Меню'),
        ),
    ]
