# Generated by Django 5.1.4 on 2025-03-26 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_remove_submenu_menu_submenu_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_filial', to='base_app.filial', verbose_name='Филиал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_submenu', to='base_app.menu', verbose_name='Меню'),
        ),
    ]
