# Generated by Django 5.1.4 on 2025-03-26 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_submenu_filial_alter_submenu_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='filial',
        ),
    ]
