# Generated by Django 5.1.4 on 2025-03-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_remove_submenu_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='filial',
            field=models.ManyToManyField(related_name='menu_filial', to='base_app.contracts', verbose_name='Филиал'),
        ),
    ]
