# Generated by Django 5.1.4 on 2025-03-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_rename_filial_submenu_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='contract',
            field=models.ManyToManyField(blank=True, null=True, related_name='menu_filial', to='base_app.contracts', verbose_name='Филиал'),
        ),
    ]
