# Generated by Django 5.1.7 on 2025-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_alter_submenu_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='contract',
            field=models.ManyToManyField(related_name='menu_filial', to='base_app.contracts', verbose_name='Филиал'),
        ),
    ]
