# Generated by Django 5.1.7 on 2025-03-27 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0016_alter_submenu_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemid', models.CharField(max_length=155)),
                ('Qty', models.IntegerField()),
                ('SalesId', models.CharField(max_length=155)),
                ('InventLocationId', models.CharField(max_length=155)),
                ('ConsigneeAccount', models.CharField(max_length=155)),
                ('DeliveryDate', models.DateField()),
                ('ManDate', models.DateField()),
                ('SalesUnit', models.CharField(default='шт', max_length=155)),
                ('Delivery', models.IntegerField(default=2)),
                ('Redelivery', models.IntegerField(default=1)),
                ('OrderType', models.IntegerField(default=1)),
                ('Comment', models.CharField(max_length=155)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.contracts')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemid', models.CharField(max_length=155)),
                ('Qty', models.IntegerField()),
                ('PurchId', models.CharField(max_length=155)),
                ('InventLocationId', models.CharField(max_length=155)),
                ('VendAccount', models.CharField(max_length=155)),
                ('DeliveryDate', models.DateField()),
                ('PurchUnit', models.CharField(default='шт', max_length=155)),
                ('PurchTTN', models.IntegerField(default=1)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.contracts')),
            ],
        ),
    ]
