# Generated by Django 5.1.7 on 2025-04-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0002_basemodel_applicationorderitems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('program_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('level_id', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('group_id', models.IntegerField()),
                ('contact_phone', models.CharField(blank=True, max_length=155, null=True)),
                ('contact_face', models.CharField(blank=True, max_length=155, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_dovoz_id', models.IntegerField()),
                ('agent_id', models.IntegerField()),
                ('ex_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
