# Generated by Django 5.1.7 on 2025-04-01 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0006_alter_invoice_date_create_alter_invoice_date_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='acs_number',
            field=models.CharField(max_length=155, verbose_name='Номер накладной'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='ut.agent', verbose_name='ИД Агента'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comment',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_create',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_doc',
            field=models.DateTimeField(verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery',
            field=models.BooleanField(verbose_name='Признак доставки'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_from', to='ut.agent', verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='from_req_id',
            field=models.IntegerField(verbose_name='От имени'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ИД'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type_id',
            field=models.IntegerField(verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_entry',
            field=models.BooleanField(verbose_name='Проведен'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_number',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='program_id',
            field=models.IntegerField(verbose_name='ИД Программы'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_to', to='ut.agent', verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_req_id',
            field=models.IntegerField(verbose_name='На имя'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.IntegerField(verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user_create',
            field=models.CharField(max_length=155, verbose_name='Пользователь_создан'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user_update',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Пользователь_изменен'),
        ),
    ]
