# Generated by Django 5.1.7 on 2025-04-01 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0007_alter_invoice_acs_number_alter_invoice_agent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('marking_goods', models.CharField(max_length=155)),
                ('item_name', models.CharField(max_length=155)),
                ('group_id', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('shelf_life', models.IntegerField()),
                ('pieces_pkge', models.IntegerField()),
                ('amount_inblock', models.IntegerField()),
                ('amount_inbox', models.IntegerField()),
                ('amount_inpallet', models.IntegerField()),
                ('user_create', models.CharField(blank=True, max_length=155, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('user_update', models.CharField(blank=True, max_length=155, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=30)),
                ('weight_netto', models.DecimalField(decimal_places=2, max_digits=30)),
                ('length_box', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('width_box', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('height_box', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('barcode_block', models.CharField(blank=True, max_length=155, null=True)),
                ('barcode_box', models.CharField(blank=True, max_length=155, null=True)),
                ('barcode_pkge', models.CharField(blank=True, max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceBody',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=30)),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_body_goods', to='ut.goods', verbose_name='')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_body', to='ut.invoice', verbose_name='')),
            ],
        ),
    ]
