# Generated by Django 5.1.7 on 2025-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0008_goods_invoicebody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
        migrations.AlterField(
            model_name='goods',
            name='weight_netto',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
    ]
