# Generated by Django 5.1.7 on 2025-04-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0009_alter_goods_weight_alter_goods_weight_netto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_dovoz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ut.agent'),
        ),
    ]
