# Generated by Django 5.1.7 on 2025-04-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0010_alter_agent_agent_dovoz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_dovoz_id',
            field=models.IntegerField(),
        ),
    ]
