# Generated by Django 5.1.7 on 2025-04-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ut', '0012_alter_agent_address_alter_agent_agent_dovoz_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='from_req_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='to_req_id',
        ),
    ]
