# Generated by Django 5.1.5 on 2025-02-11 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('program_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('level_id', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('group_id', models.IntegerField()),
                ('contact_phone', models.CharField(blank=True, max_length=155, null=True)),
                ('contact_face', models.CharField(blank=True, max_length=155, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('marking_goods', models.CharField(max_length=155)),
                ('item_name', models.CharField(max_length=155)),
                ('group_id', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('shelf_life', models.IntegerField()),
                ('pieces_pkge', models.IntegerField()),
                ('amount_inblock', models.IntegerField()),
                ('amount_inbox', models.IntegerField()),
                ('amount_inpallet', models.IntegerField()),
                ('user_create', models.CharField(blank=True, max_length=155, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('user_update', models.CharField(blank=True, max_length=155, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=30)),
                ('weight_netto', models.DecimalField(decimal_places=2, max_digits=30)),
                ('length_box', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('width_box', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('height_box', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('barcode_block', models.CharField(blank=True, max_length=155, null=True)),
                ('barcode_box', models.CharField(blank=True, max_length=155, null=True)),
                ('barcode_pkge', models.CharField(blank=True, max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('program_id', models.IntegerField(verbose_name='')),
                ('acs_number', models.CharField(max_length=155, verbose_name='')),
                ('is_active', models.BooleanField(verbose_name='')),
                ('date_doc', models.DateField(verbose_name='')),
                ('is_entry', models.BooleanField(verbose_name='')),
                ('invoice_type_id', models.IntegerField(choices=[(103, 'Order'), (203, 'Porder')], verbose_name='')),
                ('from_req_id', models.IntegerField(verbose_name='')),
                ('to_req_id', models.IntegerField(verbose_name='')),
                ('date_create', models.DateField(verbose_name='')),
                ('date_update', models.DateField(blank=True, null=True, verbose_name='')),
                ('comment', models.CharField(blank=True, max_length=155, null=True, verbose_name='')),
                ('user_create', models.CharField(max_length=155, verbose_name='')),
                ('user_update', models.CharField(blank=True, max_length=155, null=True, verbose_name='')),
                ('delivery', models.BooleanField(verbose_name='')),
                ('uid', models.IntegerField(verbose_name='')),
                ('order_number', models.CharField(blank=True, max_length=155, null=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='krd.agent', verbose_name='')),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_from', to='krd.agent', verbose_name='')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_to', to='krd.agent', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceBody',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=30)),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_body_goods', to='krd.goods', verbose_name='')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_body', to='krd.invoice', verbose_name='')),
            ],
        ),
    ]
