# Generated by Django 5.1.5 on 2025-03-07 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ('id', 'item_name'), 'verbose_name': 'Агент', 'verbose_name_plural': 'Агенты'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ('id', 'marking_goods'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_doc'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='invoicebody',
            options={'ordering': ('id', 'invoice_id', 'goods_id'), 'verbose_name': 'Строка операции', 'verbose_name_plural': 'Строки операций'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='acs_number',
            field=models.CharField(max_length=155, verbose_name='Номер накладной'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='krd.agent', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comment',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_create',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_doc',
            field=models.DateField(verbose_name='Дата накладной'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_update',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery',
            field=models.BooleanField(verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_from', to='krd.agent', verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='from_req_id',
            field=models.IntegerField(verbose_name='От имени'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type_id',
            field=models.IntegerField(choices=[(103, 'Order'), (203, 'Porder')], verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_entry',
            field=models.BooleanField(verbose_name='Проведен'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_number',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='program_id',
            field=models.IntegerField(verbose_name='Код программы'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_to', to='krd.agent', verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_req_id',
            field=models.IntegerField(verbose_name='На имя'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.IntegerField(verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user_create',
            field=models.CharField(max_length=155, verbose_name='Создан пользователем'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user_update',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Изменен пользователем'),
        ),
    ]
